import { defineStore } from "pinia"

export const useLADataStore = defineStore("laData", {
    state: (): ISheetRows => ({
        rows: [],
        isDataLoaded: false,
        cities: [
            "All Cities",
            "Alhambra",
            "Anaheim",
            "Arcadia",
            "Azusa",
            "Baldwin Park",
            "Beverly Hills",
            "Bradbury",
            "Carson",
            "Cudahy",
            "Culver",
            "Diamond Bar",
            "Duarte",
            "El Monte",
            "Gardena",
            "Inglewood",
            "Irwindale",
            "La Puente",
            "La Verne",
            "Lawndale",
            "Lomita",
            "Malibu",
            "Manhattan Beach",
            "Monterey Park",
            "Norwalk",
            "Oakland",
            "Pico Rivera",
            "Riverside",
            "Rolling Hills",
            "Rolling Hills Estates",
            "San Gabriel",
            "Santa Monica",
            "Signal Hill",
            "South El Monte",
            "Temple",
            "Ventura",
            "Walnut",
            "West Covina",
        ],
    }),
    actions: {},
    getters: {},
})
